services:
  - type: web
    name: project-management
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn project_management.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: project-db
          property: connectionString

databases:
  - name: project-db
